version: "3.7"
services:
  redis:
    image: "redis:latest"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  api:
    build: ./server
    links:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/api/
    depends_on:
      - redis
    restart: always
